### ISSUE TITLE
Προτείνω #feature εξαγωγής λέξεων κλειδιών από άρθρο

### ISSUE THREAD

**Issue by ghost** [Savinos90/sociopub#21]
From: salexa03@cs.ucy.ac.cy<br><br>
&Sigma;&epsilon;&nu;&#940;&rho;&iota;&omicron;: &epsilon;&mu;&phi;&#940;&nu;&iota;&sigma;&eta;&sigmaf; &lambda;&#941;&xi;&epsilon;&omega;&nu; &kappa;&lambda;&epsilon;&iota;&delta;&iota;&#974;&nu; - &epsilon;&tau;&iota;&kappa;&epsilon;&tau;&#974;&nu; &#940;&rho;&theta;&rho;&omicron;&upsilon;<br>
&#908;&tau;&alpha;&nu; &zeta;&eta;&tau;&#974; &nu;&alpha; &delta;&iota;&alpha;&beta;&#940;&sigma;&omega; &tau;&eta;&nu; &epsilon;&phi;&eta;&mu;&epsilon;&rho;&#943;&delta;&alpha;<br>
&Tau;&#972;&tau;&epsilon; &sigma;&epsilon; &kappa;&#940;&theta;&epsilon; &#940;&rho;&theta;&rho;&omicron; &nu;&alpha; &epsilon;&mu;&phi;&alpha;&nu;&#943;&zeta;&omicron;&nu;&tau;&alpha;&iota; &lambda;&#941;&xi;&epsilon;&iota;&sigmaf; &kappa;&lambda;&epsilon;&iota;&delta;&iota;&#940; &alpha;&pi;&#972; &tau;&omicron; &kappa;&epsilon;&#943;&mu;&epsilon;&nu;&omicron;<br><br><br>
First Attachment if exist: http://ift.tt/19fNRe4<br>

**Comment by savvasal** [comment]
Κάποιες από αυτές δεν εξάγουν περιεχόμενο - γι αυτό έχει οριστεί καινούργια λειτουργία [επισύμανσης ιστοσελίδας ως συμβατή με την εφαρμογή](https://github.com/Savinos90/sociopub/issues/25).
